name: TRIPS CICD

env:
  poi_path: apis/trips/**
  registry: openhackr6a3ic71acr.azurecr.io
  repository: devopsoh/api-trips
  docker_path: apis/trips
  build_name: TRIPS

on:
  push:
    branches: [ master ]
    paths: 
      - apis/trips/**  
      - .github/workflows/trips.yml
  pull_request:
    branches: [ master ]
    paths: 
      - apis/trips/**
      - .github/workflows/trips.yml

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3
      with:
        go-version: 1.12

    - name: Install dependencies
      run: go get

    - name: Run Unit Tests
      run: go test ./tests

    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
          
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with:
        app-name: openhackr6a3ic71trips
        images: openhackr6a3ic71acr.azurecr.io/devopsoh/api-trips:${{github.run_number}}  
